
version: 2
jobs:
  build-and-test:
    working_directory: ~/camerakit-website
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
  deploy:
    machine:
      enabled: true
    working_directory: ~/camerakit-website
    environment:
      HEROKU_APP: "camerakit-website"
    steps:
      - checkout
      - run:
        command: |
          heroku container:login
          heroku container:push web
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy
        requires:
          - build-and-test
        #filters:
          #branches:
            #only: master
